### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by shittyfollower** [Greenwolf/ntlm_theft#3]
This is awesome.

Are there plans to add anymore?

Anyway to embed NTLM theft in images?

**Comment by shittyfollower** [comment]
Going to have a play around with this feature:

https://support.winzip.com/hc/en-us/articles/115011592207-Explanation-of-Unzip-automatically-and-the-auto-command-line-switch#:~:text=WinZip%20Self%2DExtractor%20has%20the,successful%2C%20clicking%20the%20Close%20button.

**Comment by Greenwolf** [comment]
If you discover any more techniques and I will happily add them in. 

I don't believe there are any in for images though.
